# Generated by Django 5.2.4 on 2025-07-26 08:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OjtUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ojt_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('ongoing', 'Ongoing')], default='pending', max_length=20)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('company_address', models.TextField(blank=True, null=True)),
                ('supervisor_name', models.CharField(blank=True, max_length=255, null=True)),
                ('supervisor_contact', models.CharField(blank=True, max_length=50, null=True)),
                ('supervisor_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('total_hours', models.IntegerField(default=0)),
                ('position_title', models.CharField(blank=True, max_length=255, null=True)),
                ('department', models.CharField(blank=True, max_length=255, null=True)),
                ('stipend_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('requirements_submitted', models.BooleanField(default=False)),
                ('evaluation_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ojt_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'OJT User',
                'verbose_name_plural': 'OJT Users',
                'db_table': 'ojt_users',
            },
        ),
    ]
