# Generated by Django 5.2.3 on 2025-07-28 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ojt_users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OjtUser',
        ),
    ]
