# Generated by Django 5.2.4 on 2025-07-17 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0006_notification_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackerform',
            name='accepting_responses',
            field=models.BooleanField(default=True),
        ),
    ]
