# Generated by Django 5.2.3 on 2025-07-20 04:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0008_alter_trackerform_standard'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackerFileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.IntegerField()),
                ('file', models.FileField(upload_to='tracker_uploads/')),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size', models.IntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='shared.trackerresponse')),
            ],
        ),
    ]
