# Generated by Django 5.2.4 on 2025-07-20 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0005_seed_tracker_questions'),
        ('shared', '0009_trackerfileupload'),
    ]

    operations = [
    ]
