# Generated by Django 5.2.4 on 2025-07-22 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0007_ojtdata_ojtimport'),
        ('shared', '0009_trackerfileupload'),
    ]

    operations = [
    ]
