# Generated by Django 5.2.4 on 2025-07-20 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0010_merge_20250721_0038'),
    ]

    operations = [
        migrations.AddField(
            model_name='questioncategory',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
