# Generated by Django 5.2.4 on 2025-07-22 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0011_user_ojtstatus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OJTData',
        ),
        migrations.AddField(
            model_name='accounttype',
            name='ojt',
            field=models.BooleanField(default=False),
        ),
    ]
