# Generated by Django 5.2.4 on 2025-07-20 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0011_questioncategory_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='aacup',
            name='high_position_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ched',
            name='awards_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ched',
            name='gov_position_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='qpro',
            name='further_study_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='suc',
            name='average_salary',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='suc',
            name='employment_status_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='suc',
            name='job_alignment_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='suc',
            name='self_employed_count',
            field=models.IntegerField(default=0),
        ),
    ]
