# Generated by Django 5.2.4 on 2025-07-21 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0012_aacup_high_position_count_ched_awards_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aacup',
            name='awards_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aacup',
            name='entrepreneurship_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aacup',
            name='self_employed_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ched',
            name='further_study_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ched',
            name='self_employed_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='qpro',
            name='current_position',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='qpro',
            name='employed_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='qpro',
            name='unemployed_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='suc',
            name='further_study_count',
            field=models.IntegerField(default=0),
        ),
    ]
