# Generated by Django 5.2.4 on 2025-07-21 01:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0013_aacup_awards_count_aacup_entrepreneurship_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ched',
            name='comp_tech_jobs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ched_comptechjobs', to='shared.comptechjob'),
        ),
        migrations.AddField(
            model_name='ched',
            name='info_system_jobs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ched_infosystemjobs', to='shared.infosystemjob'),
        ),
        migrations.AddField(
            model_name='ched',
            name='info_tech_jobs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ched_infotechjobs', to='shared.infotechjob'),
        ),
        migrations.AddField(
            model_name='ched',
            name='job_alignment_count',
            field=models.IntegerField(default=0),
        ),
    ]
