# Generated by Django 5.1.5 on 2025-07-21 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0014_ched_comp_tech_jobs_ched_info_system_jobs_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='status',
        ),
    ]
