# Generated by Django 5.2.3 on 2025-07-25 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0015_remove_user_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackerform',
            name='standard',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tracker_forms', to='shared.standard'),
            preserve_default=False,
        ),
    ]
