# Generated by Django 5.2.4 on 2025-07-22 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0015_remove_user_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aacup',
            name='awards_count',
        ),
        migrations.RemoveField(
            model_name='aacup',
            name='entrepreneurship_count',
        ),
        migrations.RemoveField(
            model_name='aacup',
            name='high_position_count',
        ),
        migrations.RemoveField(
            model_name='aacup',
            name='self_employed_count',
        ),
        migrations.RemoveField(
            model_name='ched',
            name='awards_count',
        ),
        migrations.RemoveField(
            model_name='ched',
            name='comp_tech_jobs',
        ),
        migrations.RemoveField(
            model_name='ched',
            name='further_study_count',
        ),
        migrations.RemoveField(
            model_name='ched',
            name='gov_position_count',
        ),
        migrations.RemoveField(
            model_name='ched',
            name='info_system_jobs',
        ),
        migrations.RemoveField(
            model_name='ched',
            name='info_tech_jobs',
        ),
        migrations.RemoveField(
            model_name='ched',
            name='job_alignment_count',
        ),
        migrations.RemoveField(
            model_name='ched',
            name='self_employed_count',
        ),
        migrations.RemoveField(
            model_name='qpro',
            name='current_position',
        ),
        migrations.RemoveField(
            model_name='qpro',
            name='employed_count',
        ),
        migrations.RemoveField(
            model_name='qpro',
            name='further_study_count',
        ),
        migrations.RemoveField(
            model_name='qpro',
            name='unemployed_count',
        ),
        migrations.RemoveField(
            model_name='suc',
            name='average_salary',
        ),
        migrations.RemoveField(
            model_name='suc',
            name='employment_status_count',
        ),
        migrations.RemoveField(
            model_name='suc',
            name='further_study_count',
        ),
        migrations.RemoveField(
            model_name='suc',
            name='job_alignment_count',
        ),
        migrations.RemoveField(
            model_name='suc',
            name='self_employed_count',
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
