# Generated by Django 5.2.3 on 2025-07-25 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0015_remove_user_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackerform',
            name='standard',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tracker_forms', to='shared.standard'),
        ),
        migrations.RunSQL(
            # Update existing TrackerForm records to use the first available Standard
            sql="UPDATE shared_trackerform SET standard_id = (SELECT MIN(standard_id) FROM shared_standard) WHERE standard_id IS NULL;",
            reverse_sql="UPDATE shared_trackerform SET standard_id = NULL;"
        ),
        migrations.AlterField(
            model_name='trackerform',
            name='standard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracker_forms', to='shared.standard'),
        ),
    ]
