# Generated by Django 5.1.5 on 2025-07-24 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0016_remove_aacup_awards_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='status',
        ),
        migrations.AddField(
            model_name='user',
            name='job_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
