# Generated by Django 5.1.5 on 2025-07-26 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0017_remove_user_status_user_job_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standard',
            name='aacup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='standards', to='shared.aacup'),
        ),
        migrations.AlterField(
            model_name='standard',
            name='ched',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='standards', to='shared.ched'),
        ),
        migrations.AlterField(
            model_name='standard',
            name='qpro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='standards', to='shared.qpro'),
        ),
        migrations.AlterField(
            model_name='standard',
            name='suc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='standards', to='shared.suc'),
        ),
    ]
