# Generated by Django 5.1.5 on 2025-07-26 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0018_make_standard_foreign_keys_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='ched',
            name='job_alignment_count',
            field=models.IntegerField(default=0),
        ),
    ]
