# Generated by Django 5.2.3 on 2025-07-28 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0012_delete_ojtdata_accounttype_ojt'),
        ('shared', '0016_alter_trackerform_standard'),
        ('shared', '0019_add_job_alignment_count_to_ched'),
    ]

    operations = [
    ]
