# Generated by Django 5.2.4 on 2025-07-28 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0021_alter_user_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
    ]
