# Generated by Django 5.1.5 on 2025-07-28 15:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0022_alter_user_profile_resume'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trackerform',
            old_name='tracker_form_id',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='standard',
            name='tracker_form',
        ),
        migrations.RemoveField(
            model_name='trackerform',
            name='standard',
        ),
        migrations.RemoveField(
            model_name='trackerform',
            name='user',
        ),
        migrations.AddField(
            model_name='standard',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='standard',
            name='name',
            field=models.CharField(default='CTU Standard', max_length=255),
        ),
        migrations.AddField(
            model_name='trackerform',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trackerform',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='trackerform',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='user',
            name='q_awards_document',
            field=models.FileField(blank=True, null=True, upload_to='awards/'),
        ),
        migrations.AddField(
            model_name='user',
            name='q_awards_received',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='q_company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='q_current_position',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='q_employment_document',
            field=models.FileField(blank=True, null=True, upload_to='employment/'),
        ),
        migrations.AddField(
            model_name='user',
            name='q_employment_duration',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='q_employment_permanent',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='q_employment_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='q_employment_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='q_institution_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='q_job_sector',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='q_post_graduate_degree',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='q_pursue_study',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='q_salary_range',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='q_study_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='q_unemployment_reason',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='q_units_obtained',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='tracker_last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='user',
            name='tracker_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trackerform',
            name='title',
            field=models.CharField(default='CTU Alumni Tracker Form', max_length=255),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['user_status', 'year_graduated'], name='shared_user_user_st_b3a3ca_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['company_name_current', 'position_current'], name='shared_user_company_e1586c_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['pursue_further_study', 'year_graduated'], name='shared_user_pursue__cd2df1_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['tracker_submitted_at'], name='shared_user_tracker_3a112a_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['q_employment_status', 'year_graduated'], name='shared_user_q_emplo_18e9f6_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['q_company_name', 'q_current_position'], name='shared_user_q_compa_aabfc9_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['q_pursue_study', 'year_graduated'], name='shared_user_q_pursu_434271_idx'),
        ),
        migrations.AddConstraint(
            model_name='trackerform',
            constraint=models.CheckConstraint(condition=models.Q(('id', 1)), name='single_tracker_form'),
        ),
    ]
