# Generated by Django 5.1.5 on 2025-07-28 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0023_add_tracker_fields_to_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trackerresponse',
            name='user',
        ),
        migrations.DeleteModel(
            name='TrackerFileUpload',
        ),
        migrations.DeleteModel(
            name='TrackerResponse',
        ),
    ]
