# Generated by Django 5.1.5 on 2025-07-28 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0025_restore_tracker_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='home_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
