# Generated by Django 5.2.4 on 2025-08-03 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0023_follow'),
        ('shared', '0026_user_company_address_user_home_address'),
    ]

    operations = [
    ]
