# Generated by Django 5.2.4 on 2025-08-03 16:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0027_merge_20250803_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.ImageField(blank=True, null=True, upload_to='post_images/'),
        ),
        migrations.SeparateDatabaseAndState(
    database_operations=[
        migrations.RunSQL(
            "DROP TABLE IF EXISTS shared_follow CASCADE;",
            reverse_sql=migrations.RunSQL.noop,
        )
    ],
    state_operations=[
        # Intentionally empty: Follow was already removed elsewhere
    ],
        ),
    ]
