# Generated by Django 5.1.5 on 2025-08-08 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0028_create_default_tracker_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='job_alignment_status',
            field=models.CharField(blank=True, default='not_aligned', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='job_alignment_category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='job_alignment_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='self_employed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='high_position',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='absorbed',
            field=models.BooleanField(default=False),
        ),
    ]
