# Generated by Django 5.2.4 on 2025-08-06 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0028_create_default_tracker_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ojt_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.ImageField(blank=True, null=True, upload_to='post_images/'),
        ),
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
