# Generated by Django 5.2.4

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0028_create_default_tracker_form'),
    ]

    operations = [
        # Do DB-only fixes in an idempotent way, without touching state twice
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    # Add column only if it's missing (idempotent)
                    """
                    ALTER TABLE shared_post
                    ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL;
                    """,
                    reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                    # Drop old Follow table if it still exists (idempotent)
                    "DROP TABLE IF EXISTS shared_follow CASCADE;",
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                # Leave empty on purpose: created_at likely already exists in state,
                # and Follow was already removed by a prior migration.
            ],
        ),

        # Keep your original field change (safe to run twice if identical)
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.ImageField(blank=True, null=True, upload_to='post_images/'),
        ),
    ]
