# Generated by Django 5.2.4 on 2025-08-08 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0029_add_job_alignment_fields'),
        ('shared', '0030_follow'),
    ]

    operations = [
    ]
