# Generated by Django 5.2.4 on 2025-08-09 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0028_post_created_at_alter_post_post_image_delete_follow'),
        ('shared', '0029_add_job_alignment_fields'),
        ('shared', '0030_follow'),
    ]

    operations = [
    ]
