# Generated by Django 5.2.4 on 2025-08-08 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0031_merge_0029_add_job_alignment_fields_0030_follow'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleCompTechJob',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('job_title', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SimpleInfoSystemJob',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('job_title', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SimpleInfoTechJob',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('job_title', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='comptechjob',
            name='info_system_jobs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comptechjob_infosystemjobs', to='shared.infosystemjob'),
        ),
        migrations.AlterField(
            model_name='comptechjob',
            name='info_tech_jobs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comptechjob_infotechjobs', to='shared.infotechjob'),
        ),
        migrations.AlterField(
            model_name='comptechjob',
            name='suc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comptechjob_sucs', to='shared.suc'),
        ),
        migrations.AlterField(
            model_name='infosystemjob',
            name='comp_tech_jobs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='infosystemjob_comptechjobs', to='shared.comptechjob'),
        ),
        migrations.AlterField(
            model_name='infosystemjob',
            name='info_tech_jobs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='infosystemjob_infotechjobs', to='shared.infotechjob'),
        ),
        migrations.AlterField(
            model_name='infosystemjob',
            name='suc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='infosystemjob_sucs', to='shared.suc'),
        ),
        migrations.AlterField(
            model_name='infotechjob',
            name='comp_tech_jobs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='infotechjob_comptechjobs', to='shared.comptechjob'),
        ),
        migrations.AlterField(
            model_name='infotechjob',
            name='info_systems_jobs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='infotechjob_infosystemjobs', to='shared.infosystemjob'),
        ),
        migrations.AlterField(
            model_name='infotechjob',
            name='suc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='infotechjob_sucs', to='shared.suc'),
        ),
    ]
