# Generated by Django 5.2.4 on 2025-08-09 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0028_post_created_at_alter_post_post_image_delete_follow'),
        ('shared', '0032_simplecomptechjob_simpleinfosystemjob_and_more'),
    ]

    operations = [
    ]
