# Generated by Django 5.2.4 on 2025-08-09 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0032_simplecomptechjob_simpleinfosystemjob_and_more'),
    ]

    operations = [
    ]
