# Generated by Django 5.2.4 on 2025-08-11 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0033_merge_20250809_1858'),
    ]

    operations = [
    ]
