# Generated by Django 5.2.4 on 2025-08-10 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ('shared', '0029_user_ojt_end_date_alter_post_post_image_and_more'),
    ('shared', '0033_merge_20250810_1232'),
    ]

    operations = [
    ]
