# Generated by Django 5.2.4 on 2025-08-11 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0034_auto_20250811_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ojt_end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
