# Generated by Django 5.2.3 on 2025-08-11 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0033_merge_20250809_1858'),
        ('shared', '0035_ensure_ojt_end_date_column'),
    ]

    operations = [
    ]
