# Generated by Django 5.2.3 on 2025-08-11 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0036_merge_20250811_1528'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='created_at',
        ),
    ]
