# Generated by Django 5.2.4 on 2025-08-20 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0036_merge_20250811_1718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='created_at',
        ),
    ]
