# Generated by Django 5.1.5 on 2025-08-19 08:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0036_merge_20250816_1627'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_graduated', models.IntegerField(blank=True, null=True)),
                ('course', models.CharField(blank=True, max_length=100, null=True)),
                ('program', models.CharField(blank=True, max_length=100, null=True)),
                ('section', models.CharField(blank=True, max_length=50, null=True)),
                ('school_name', models.CharField(blank=True, max_length=255, null=True)),
                ('pursue_further_study', models.CharField(blank=True, max_length=10, null=True)),
                ('q_pursue_study', models.CharField(blank=True, max_length=10, null=True)),
                ('q_study_start_date', models.DateField(blank=True, null=True)),
                ('q_post_graduate_degree', models.CharField(blank=True, max_length=255, null=True)),
                ('q_institution_name', models.CharField(blank=True, max_length=255, null=True)),
                ('q_units_obtained', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmploymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name_current', models.CharField(blank=True, max_length=255, null=True)),
                ('position_current', models.CharField(blank=True, max_length=255, null=True)),
                ('sector_current', models.CharField(blank=True, max_length=255, null=True)),
                ('employment_duration_current', models.CharField(blank=True, max_length=100, null=True)),
                ('salary_current', models.CharField(blank=True, max_length=100, null=True)),
                ('date_started', models.DateField(blank=True, null=True)),
                ('company_address', models.TextField(blank=True, null=True)),
                ('job_alignment_status', models.CharField(blank=True, default='not_aligned', max_length=50, null=True)),
                ('job_alignment_category', models.CharField(blank=True, max_length=100, null=True)),
                ('job_alignment_title', models.CharField(blank=True, max_length=255, null=True)),
                ('self_employed', models.BooleanField(default=False)),
                ('high_position', models.BooleanField(default=False)),
                ('absorbed', models.BooleanField(default=False)),
                ('awards_recognition_current', models.CharField(blank=True, max_length=255, null=True)),
                ('supporting_document_current', models.CharField(blank=True, max_length=255, null=True)),
                ('supporting_document_awards_recognition', models.CharField(blank=True, max_length=255, null=True)),
                ('unemployment_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OJTInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ojt_end_date', models.DateField(blank=True, null=True)),
                ('job_code', models.CharField(blank=True, max_length=20, null=True)),
                ('ojtstatus', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrackerData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_employment_status', models.CharField(blank=True, max_length=50, null=True)),
                ('q_employment_type', models.CharField(blank=True, max_length=100, null=True)),
                ('q_employment_permanent', models.CharField(blank=True, max_length=20, null=True)),
                ('q_company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('q_current_position', models.CharField(blank=True, max_length=255, null=True)),
                ('q_job_sector', models.CharField(blank=True, max_length=50, null=True)),
                ('q_employment_duration', models.CharField(blank=True, max_length=100, null=True)),
                ('q_salary_range', models.CharField(blank=True, max_length=100, null=True)),
                ('q_awards_received', models.CharField(blank=True, max_length=10, null=True)),
                ('q_awards_document', models.FileField(blank=True, null=True, upload_to='awards/')),
                ('q_employment_document', models.FileField(blank=True, null=True, upload_to='employment/')),
                ('q_unemployment_reason', models.JSONField(blank=True, null=True)),
                ('tracker_submitted_at', models.DateTimeField(blank=True, null=True)),
                ('tracker_last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_num', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('home_address', models.TextField(blank=True, null=True)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('civil_status', models.CharField(blank=True, max_length=50, null=True)),
                ('social_media', models.CharField(blank=True, max_length=255, null=True)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('profile_bio', models.TextField(blank=True, null=True)),
                ('profile_resume', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='shared_user_user_st_b3a3ca_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='shared_user_company_e1586c_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='shared_user_pursue__cd2df1_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='shared_user_tracker_3a112a_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='shared_user_q_emplo_18e9f6_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='shared_user_q_compa_aabfc9_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='shared_user_q_pursu_434271_idx',
        ),
        migrations.RemoveField(
            model_name='user',
            name='absorbed',
        ),
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='age',
        ),
        migrations.RemoveField(
            model_name='user',
            name='awards_recognition_current',
        ),
        migrations.RemoveField(
            model_name='user',
            name='birthdate',
        ),
        migrations.RemoveField(
            model_name='user',
            name='civil_status',
        ),
        migrations.RemoveField(
            model_name='user',
            name='company_address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='company_name_current',
        ),
        migrations.RemoveField(
            model_name='user',
            name='course',
        ),
        migrations.RemoveField(
            model_name='user',
            name='date_started',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='employment_duration_current',
        ),
        migrations.RemoveField(
            model_name='user',
            name='high_position',
        ),
        migrations.RemoveField(
            model_name='user',
            name='home_address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='job_alignment_category',
        ),
        migrations.RemoveField(
            model_name='user',
            name='job_alignment_status',
        ),
        migrations.RemoveField(
            model_name='user',
            name='job_alignment_title',
        ),
        migrations.RemoveField(
            model_name='user',
            name='job_code',
        ),
        migrations.RemoveField(
            model_name='user',
            name='ojt_end_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='ojtstatus',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_num',
        ),
        migrations.RemoveField(
            model_name='user',
            name='position_current',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_bio',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_pic',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_resume',
        ),
        migrations.RemoveField(
            model_name='user',
            name='program',
        ),
        migrations.RemoveField(
            model_name='user',
            name='pursue_further_study',
        ),
        migrations.RemoveField(
            model_name='user',
            name='q_awards_document',
        ),
        migrations.RemoveField(
            model_name='user',
            name='q_awards_received',
        ),
        migrations.RemoveField(
            model_name='user',
            name='q_company_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='q_current_position',
        ),
        migrations.RemoveField(
            model_name='user',
            name='q_employment_document',
        ),
        migrations.RemoveField(
            model_name='user',
            name='q_employment_duration',
        ),
        migrations.RemoveField(
            model_name='user',
            name='q_employment_permanent',
        ),
        migrations.RemoveField(
            model_name='user',
            name='q_employment_status',
        ),
        migrations.RemoveField(
            model_name='user',
            name='q_employment_type',
        ),
        migrations.RemoveField(
            model_name='user',
            name='q_institution_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='q_job_sector',
        ),
        migrations.RemoveField(
            model_name='user',
            name='q_post_graduate_degree',
        ),
        migrations.RemoveField(
            model_name='user',
            name='q_pursue_study',
        ),
        migrations.RemoveField(
            model_name='user',
            name='q_salary_range',
        ),
        migrations.RemoveField(
            model_name='user',
            name='q_study_start_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='q_unemployment_reason',
        ),
        migrations.RemoveField(
            model_name='user',
            name='q_units_obtained',
        ),
        migrations.RemoveField(
            model_name='user',
            name='salary_current',
        ),
        migrations.RemoveField(
            model_name='user',
            name='school_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='section',
        ),
        migrations.RemoveField(
            model_name='user',
            name='sector_current',
        ),
        migrations.RemoveField(
            model_name='user',
            name='self_employed',
        ),
        migrations.RemoveField(
            model_name='user',
            name='social_media',
        ),
        migrations.RemoveField(
            model_name='user',
            name='supporting_document_awards_recognition',
        ),
        migrations.RemoveField(
            model_name='user',
            name='supporting_document_current',
        ),
        migrations.RemoveField(
            model_name='user',
            name='tracker_last_updated',
        ),
        migrations.RemoveField(
            model_name='user',
            name='tracker_submitted_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='unemployment_reason',
        ),
        migrations.RemoveField(
            model_name='user',
            name='year_graduated',
        ),
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='acc_password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['user_status'], name='shared_user_user_st_bb4796_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['acc_username'], name='shared_user_acc_use_90120a_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['f_name', 'l_name'], name='shared_user_f_name_585897_idx'),
        ),
        migrations.AddField(
            model_name='academicinfo',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='academic_info', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employmenthistory',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ojtinfo',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ojt_info', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trackerdata',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tracker_data', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='academicinfo',
            index=models.Index(fields=['year_graduated', 'course'], name='shared_acad_year_gr_8d0e79_idx'),
        ),
        migrations.AddIndex(
            model_name='academicinfo',
            index=models.Index(fields=['pursue_further_study'], name='shared_acad_pursue__15a11a_idx'),
        ),
        migrations.AddIndex(
            model_name='employmenthistory',
            index=models.Index(fields=['company_name_current', 'position_current'], name='shared_empl_company_1f0ca3_idx'),
        ),
        migrations.AddIndex(
            model_name='employmenthistory',
            index=models.Index(fields=['job_alignment_status'], name='shared_empl_job_ali_8945f3_idx'),
        ),
        migrations.AddIndex(
            model_name='employmenthistory',
            index=models.Index(fields=['self_employed', 'high_position'], name='shared_empl_self_em_ebd2af_idx'),
        ),
        migrations.AddIndex(
            model_name='ojtinfo',
            index=models.Index(fields=['ojtstatus'], name='shared_ojti_ojtstat_911886_idx'),
        ),
        migrations.AddIndex(
            model_name='ojtinfo',
            index=models.Index(fields=['ojt_end_date'], name='shared_ojti_ojt_end_a1afc9_idx'),
        ),
        migrations.AddIndex(
            model_name='trackerdata',
            index=models.Index(fields=['q_employment_status'], name='shared_trac_q_emplo_676ad0_idx'),
        ),
        migrations.AddIndex(
            model_name='trackerdata',
            index=models.Index(fields=['tracker_submitted_at'], name='shared_trac_tracker_664665_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['civil_status'], name='shared_user_civil_s_911a9f_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['age'], name='shared_user_age_d7322f_idx'),
        ),
    ]
