# Generated by Django 5.2.3 on 2025-08-21 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0037_academicinfo_employmenthistory_ojtinfo_trackerdata_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInitialPassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password_encrypted', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exported_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='initial_password', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
