# Generated by Django 5.2.3 on 2025-09-02 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0036_merge_20250811_1528'),
        ('shared', '0038_userinitialpassword'),
    ]

    operations = [
    ]
