# Generated by Django 5.2.3 on 2025-08-26 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0038_userinitialpassword'),
        ('shared', '0039_add_created_at_back_to_post'),
    ]

    operations = [
    ]
