# Generated by Django 5.2.3 on 2025-09-02 05:54

from django.db import migrations, models
import django.db.models.deletion


def backfill_message_fields(apps, schema_editor):
    Message = apps.get_model('shared', 'Message')
    for msg in Message.objects.all().only('message_id'):
        content = getattr(msg, 'message_content', None)
        created = getattr(msg, 'date_send', None)
        if content is not None:
            msg.content = content
        if created is not None:
            msg.created_at = created
        if not getattr(msg, 'message_type', None):
            msg.message_type = 'text'
        if getattr(msg, 'is_read', None) is None:
            msg.is_read = False
        msg.save(update_fields=['content', 'created_at', 'message_type', 'is_read'])


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0040_add_messaging_models'),
    ]

    operations = [
        # Ensure shared_conversation exists (earlier migration was faked)
        migrations.RunSQL(
            sql=(
                """
                CREATE TABLE IF NOT EXISTS public.shared_conversation (
                    conversation_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
                );
                """
            ),
            reverse_sql=(
                """
                -- Do not drop in reverse to avoid data loss
                """
            ),
        ),
        # Ensure shared_messageattachment exists (earlier migration was faked)
        migrations.RunSQL(
            sql=(
                """
                CREATE TABLE IF NOT EXISTS public.shared_messageattachment (
                    attachment_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    file VARCHAR(100) NOT NULL,
                    file_name VARCHAR(255) NOT NULL,
                    file_type VARCHAR(50) NOT NULL,
                    file_size INTEGER NOT NULL,
                    uploaded_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                    message_id INTEGER NOT NULL
                );
                """
            ),
            reverse_sql=(
                """
                -- Do not drop in reverse to avoid data loss
                """
            ),
        ),

        # Add new columns to shared_message if legacy table exists
        migrations.AddField(
            model_name='message',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='message_type',
            field=models.CharField(max_length=20, default='text', choices=[('text', 'Text'), ('image', 'Image'), ('file', 'File'), ('system', 'System')]),
        ),
        migrations.AddField(
            model_name='message',
            name='conversation',
            field=models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='shared.conversation'),
        ),

        # Backfill new fields from legacy columns
        migrations.RunPython(backfill_message_fields, migrations.RunPython.noop),

        # Make created_at non-nullable after backfill
        migrations.AlterField(
            model_name='message',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
