# Generated by Django 5.2.4 on 2025-08-31 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0036_merge_20250811_1528'),
        ('shared', '0040_merge_20250826_2137'),
    ]

    operations = [
    ]
