# Generated by Django 5.2.3 on 2025-09-02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0041_messaging_align_existing'),
    ]

    operations = [
        # M2M table for conversation participants
        migrations.RunSQL(
            sql=(
                """
                CREATE TABLE IF NOT EXISTS public.shared_conversation_participants (
                    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    conversation_id INTEGER NOT NULL,
                    user_id INTEGER NOT NULL
                );
                CREATE UNIQUE INDEX IF NOT EXISTS shared_conv_part_unique ON public.shared_conversation_participants (conversation_id, user_id);
                CREATE INDEX IF NOT EXISTS shared_conv_part_conv_idx ON public.shared_conversation_participants (conversation_id);
                CREATE INDEX IF NOT EXISTS shared_conv_part_user_idx ON public.shared_conversation_participants (user_id);
                DO $$
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1 FROM information_schema.table_constraints WHERE constraint_name = 'shared_conv_part_conv_fk'
                    ) THEN
                        ALTER TABLE public.shared_conversation_participants
                            ADD CONSTRAINT shared_conv_part_conv_fk FOREIGN KEY (conversation_id)
                            REFERENCES public.shared_conversation (conversation_id) DEFERRABLE INITIALLY DEFERRED;
                    END IF;
                    IF NOT EXISTS (
                        SELECT 1 FROM information_schema.table_constraints WHERE constraint_name = 'shared_conv_part_user_fk'
                    ) THEN
                        ALTER TABLE public.shared_conversation_participants
                            ADD CONSTRAINT shared_conv_part_user_fk FOREIGN KEY (user_id)
                            REFERENCES public.shared_user (user_id) DEFERRABLE INITIALLY DEFERRED;
                    END IF;
                END$$;
                """
            ),
            reverse_sql=(
                """
                -- No reverse drop to avoid data loss
                """
            ),
        ),
        # FK for messageattachment.message_id -> shared_message
        migrations.RunSQL(
            sql=(
                """
                DO $$
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1 FROM information_schema.table_constraints 
                        WHERE constraint_name = 'shared_msgatt_message_fk'
                    ) THEN
                        ALTER TABLE public.shared_messageattachment
                            ADD CONSTRAINT shared_msgatt_message_fk FOREIGN KEY (message_id)
                            REFERENCES public.shared_message (message_id) DEFERRABLE INITIALLY DEFERRED;
                    END IF;
                END$$;
                CREATE INDEX IF NOT EXISTS shared_msgatt_message_idx ON public.shared_messageattachment (message_id);
                """
            ),
            reverse_sql=(
                """
                -- No reverse to avoid data loss
                """
            ),
        ),
    ]
