# Generated by Django 5.2.3 on 2025-09-03 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0042_messaging_m2m_and_constraints'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='message',
            new_name='shared_mess_convers_108cd8_idx',
            old_name='shared_message_convers_created_idx',
        ),
        migrations.RenameIndex(
            model_name='message',
            new_name='shared_mess_sender__325014_idx',
            old_name='shared_message_sender_created_idx',
        ),
        migrations.RenameIndex(
            model_name='message',
            new_name='shared_mess_is_read_1f93c2_idx',
            old_name='shared_message_is_read_idx',
        ),
        migrations.RenameIndex(
            model_name='messageattachment',
            new_name='shared_mess_message_426449_idx',
            old_name='shared_messageattachment_message_uploaded_idx',
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(blank=True, default=''),
        ),
    ]
