# Generated by Django 5.2.3 on 2025-06-18 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_username', models.CharField(max_length=50, unique=True)),
                ('acc_password', models.DateField()),
                ('f_name', models.CharField(max_length=100)),
                ('l_name', models.CharField(max_length=100)),
                ('year_graduated', models.CharField(max_length=4)),
            ],
        ),
    ]
