# Generated by Django 5.2.4 on 2025-07-11 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0004_questioncategory_question_trackerresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackerform',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
