# Generated by Django 5.2.4 on 2025-07-22 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0010_merge_0007_ojtdata_ojtimport_0009_trackerfileupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ojtstatus',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
