# Generated by Django 5.2.4 on 2025-07-20 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0006_notification_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='OJTData',
            fields=[
                ('ojt_id', models.AutoField(primary_key=True, serialize=False)),
                ('ctu_id', models.CharField(max_length=100, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('birthdate', models.DateField()),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('civil_status', models.CharField(blank=True, max_length=50, null=True)),
                ('social_media', models.CharField(blank=True, max_length=255, null=True)),
                ('ojt_company', models.CharField(blank=True, max_length=255, null=True)),
                ('ojt_position', models.CharField(blank=True, max_length=255, null=True)),
                ('ojt_start_date', models.DateField(blank=True, null=True)),
                ('ojt_end_date', models.DateField(blank=True, null=True)),
                ('ojt_supervisor', models.CharField(blank=True, max_length=255, null=True)),
                ('ojt_performance_rating', models.CharField(blank=True, max_length=50, null=True)),
                ('ojt_certificate', models.CharField(blank=True, max_length=255, null=True)),
                ('ojt_status', models.CharField(default='Pending', max_length=50)),
                ('ojt_remarks', models.TextField(blank=True, null=True)),
                ('imported_by', models.CharField(blank=True, max_length=100, null=True)),
                ('import_date', models.DateTimeField(auto_now_add=True)),
                ('batch_year', models.IntegerField(blank=True, null=True)),
                ('course', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OJTImport',
            fields=[
                ('import_id', models.AutoField(primary_key=True, serialize=False)),
                ('coordinator', models.CharField(max_length=100)),
                ('batch_year', models.IntegerField()),
                ('course', models.CharField(max_length=100)),
                ('import_date', models.DateTimeField(auto_now_add=True)),
                ('file_name', models.CharField(max_length=255)),
                ('records_imported', models.IntegerField(default=0)),
                ('status', models.CharField(default='Completed', max_length=50)),
            ],
        ),
    ]
