# Generated by Django 5.2.4 on 2025-07-18 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0007_trackerform_accepting_responses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackerform',
            name='standard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tracker_forms', to='shared.standard'),
        ),
    ]
